### ISSUE TITLE
how to debug creepjs app

### ISSUE THREAD

**Issue by darkworks** [abrahamjuliot/creepjs#146]
Am wondering is there is debug option in creepjs app ?
i have added this tool to my website on local its working ok but on my live website its not working not sure what wrong with it it not throw any error etc that could indicate issue. 
to me seems like creepjs have some problem with letsencrypt certificates , as on local i do not have letsencrypt certificates i have self signed https certificates and the sites working ok

so can u check it a bit to see what could be wrong with it its up to date with your github repo.
live version on my website : https://www.useotools.com/ur-privacy-checker

thanks

**Comment by abrahamjuliot** [comment]
Thank you for reporting this. I can confirm on your site the service worker is hanging on the `ready`. I'm not sure why that is, but a quick fix is to use `getRegistration(source)` instead of `ready`. I went ahead and merged this if you want to import the change.

```js
const registration = await navigator.serviceWorker.ready // On your site, this hangs and never resolves 
```
```js
// solution
const registration = await navigator.serviceWorker.getRegistration(source)
```

In regards to debgging, I have some very basic logs hinting what functions have not yet succeed. With that I was able to narrow it down to workers, and then I used Chrome dev tool local overrides on your site to manually debug log results.

On the subject of your site, you may notice the template CSS will need some cleaning up. As an alternative, you might be able to host the page on a standalone html index and then import via an iframe. That should prevent the style conflict.

It's on my mind to create a Creep JS Lite (just JavaScript) that would make it easy to import on any site. With that devs can create a custom display with the data.

**Comment by darkworks** [comment]
thanks ok i will update it and then will try again :), i had tried with iframe however with iframe the app not works very well showing blocked

![image](https://user-images.githubusercontent.com/12841788/131449034-65a7bf7f-4361-445e-9bd2-04c77054f714.png)

**Comment by darkworks** [comment]
thanks now its working ok , however i noticed that on brave browser the predication info is no longer shown it might be due to recent update

![image](https://user-images.githubusercontent.com/12841788/131450870-29e1ecf8-53f0-4e9c-806c-8c03b0104cc6.png)

not shown on brave  ( Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit) )

thanks

**Comment by darkworks** [comment]
@abrahamjuliot  hi i have updated creepjs on my site , the new version is also hanging on live , locally its ok , previously i had reported same issue and you had fixed it , now the current version have same issue again can you please check it : https://www.useotools.com/ur-privacy-checker
seems to be stuck on : X (5.20ms) features

**Comment by abrahamjuliot** [comment]
I'm now using the `ready` promise to ensure the service worker is actually ready. I'm still unsure why that promise hangs on your site. 

I could apply a catch on that error by returning undefined if it fails to register in x seconds.

For now, it should work on your site if you change `navigator.serviceWorker.ready.then` to `navigator.serviceWorker.getRegistration(scriptSource).then`

**Comment by darkworks** [comment]
> I'm now using the `ready` promise to ensure the service worker is actually ready. I'm still unsure why that promise hangs on your site.
> 
> I could apply a catch on that error by returning undefined if it fails to register in x seconds.
> 
> For now, it should work on your site if you change `navigator.serviceWorker.ready.then` to `navigator.serviceWorker.getRegistration(scriptSource).then`

thanks for the fix
