### ISSUE TITLE
False positive when Linux has Windows fonts setup as UI fonts

### ISSUE THREAD

**Issue by Snivyer1910** [abrahamjuliot/creepjs#178]
So in my Linux install I have Segoe UI (Windows Font) as the font for my UI, this creepjs detects it as a lie on the user agent and marks the OS as Windows despite the fact that it is, indeed, Linux

Will be posting screenshot soon

**Comment by Snivyer1910** [comment]
![image](https://user-images.githubusercontent.com/72054019/161888781-fce06f23-aa3f-4857-8a36-b5c319240ed0.png)

**Comment by abrahamjuliot** [comment]
The script looks for `Segoe UI Emoji` and `Segoe Fluent Icons`, but not `Segoe UI`. But, the presence of those fonts on Linux does not trigger the message you are seeing.

If your Linux OS includes `Lucida Console` and none of the following, then this would trigger the message
```
Arimo
Chilanka
Cousine
Jomolhari
MONO
Noto Color Emoji
Ubuntu
```

May I ask what fonts do have listed here when you click on the modal? It's possible my Linux list is lacking. If you are aiming to mirror a Windows setup on Linux, that's cool too.

![image](https://user-images.githubusercontent.com/6946045/162341539-9cbaa9bd-898a-4743-8c26-005b053fe1c9.png)

![image](https://user-images.githubusercontent.com/6946045/162341631-64fe416b-6370-4f31-af27-42c72b27e470.png)

**Comment by Snivyer1910** [comment]
my install is a customized endeavour, and yes I'm trying to mimic a Windows Style
this is what appears on my font selection modal, and yes Lucida Console is there
![image](https://user-images.githubusercontent.com/72054019/162371267-ab093ac0-6ece-43e6-bc68-d37d0e63b82a.png)
![image](https://user-images.githubusercontent.com/72054019/162371299-6adc4f6c-f659-43b0-8dfc-fd48cf6c7a20.png)

**Comment by Snivyer1910** [comment]
also have Lucida Console as Konsole's font, that's why it's loaded
![image](https://user-images.githubusercontent.com/72054019/162371676-ad4f94b1-2030-48fc-963f-c76863d60069.png)

**Comment by abrahamjuliot** [comment]
So, the mark of *Windows 10* in the font section is correct, but a better wording there would be *platform: Like Windows 10*. Fonts only provide hints to  the platform, and in this case the fonts are hinting to Windows 10.

On the lie message, I could change the script and let Linux pass (there are so many font possibilities on Linux), or I can make it more difficult to hide Linux fonts.  For now, I will give it thought and keep this issue open and unresolved.

At the same time, I'm not sure if I will make any changes, since I imagine it is rare for anyone to install all `Windows 10` fonts.  Also, I added the font platform lie test to prevent Linux from blending in with Windows prediction data (knowing that it's possible with little effort). It's fine if the prediction is off or in need of supervision. The goal is to learn what metrics provide the highest entropy, as opposed to 100% identifying this metric is only on x platform. 

I welcome different perspectives on this. I'm here to research and learn.

**Comment by abrahamjuliot** [comment]
This worker font lie detection is now removed.
