### ISSUE TITLE
Prediction not matching trust rate

### ISSUE THREAD

**Issue by wgladforever** [abrahamjuliot/creepjs#188]
I have specific build that passes all lie tests and receives 100% A trust score with 0 lies. The problem is that version of Chromium I was running was at 105 and the device that I was simulating was on 99. Prediction parameter that relies on fetching the features from property descriptors that include global objects from Javascript, CSS and Window features is showing that I do have some APIs / features that are not present in version 99 but rather are in version 105. The prediction itself shows when I run the test that I'm running on Chrome 105. Now I don't understand why it didn't decrease my trust score? Isn't this valid enough test to determine if a user is lying when he says that he is running older version of Chrome and overriding his UserAgent due to him having some properties such as 'container-name' from 105 which are clearly not present in version 99 that he claims he is on?

**Comment by abrahamjuliot** [comment]
I'm hesitant to rely too much on features to determine trust, since there are legitimate reasons for stable features to be disabled or new unstable features to be tested. This is definitely anomalous behavior that makes one highly unique. I could send the discrepancy to the trash and that will affect the score.
