### ISSUE TITLE
Improve font lists

### ISSUE THREAD

**Issue by igor-lemon** [abrahamjuliot/creepjs#232]
Hi. You added these fonts for like Apple platform

```
const isLikeApple = (
  'Helvetica Neue' in fontMap ||
  'Luminari' in fontMap ||
  'PingFang HK Light' in fontMap ||
  'Futura Bold' in fontMap ||
  'InaiMathi Bold' in fontMap ||
  'Galvji' in fontMap ||
  'Chakra Petch' in fontMap
)
```

But `Futura Bold` can exists on Windows too, not only macOS.
https://learn.microsoft.com/en-us/typography/font-list/futura

**Comment by abrahamjuliot** [comment]
This is okay as long as it's not a standard desktop font shipped with Windows 10 or 11 [here](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list).

**Comment by igor-lemon** [comment]
This is the wrong approach, because, for example, I did not install any extra fonts but I have `[Papyrus](https://learn.microsoft.com/en-us/typography/font-list/papyrus)`, `[Rockwell](https://learn.microsoft.com/en-us/typography/font-list/rockwell)`, `[Tw Cen MT](https://learn.microsoft.com/en-us/typography/font-list/tw-cen-mt)`. You will not find these fonts in the list but will find them in the common fonts list. 
It's strange that you don't want to fix this bug.

**Comment by abrahamjuliot** [comment]
I see this as a unique fingerprint and not a bug, but welcome different perspectives on this.

I can remove Futura Bold, but it's still possible for Windows to have any of the other fonts in the list via software installation, and without the user knowing about it. The goal is not to determine the real OS with fonts. Fonts are just hints, and accuracy in discovering the real OS is not critical. Finding stability in fingerprints and tracing patterns is the goal.

I do see it gives the wrong impression if there is inaccuracy and the user made no modifications. I will leave the issue open and revisit this list.

**Comment by abrahamjuliot** [comment]
_update_

I appreciate your interest in the code.

Futura Bold on Windows is classified as trash because it is a very rare font (0.0024643283% of Windows users) that makes the browser fingerprint unique and identifiable. The trash feature detects such uncommon features that can compromise privacy. More details are available in the documentation.

The font lists are based on data and reflect the most common and typical font configurations. Including every rare font in the list would make the trash feature less effective. Therefore, a data-driven approach is used to determine which fonts are trash and which are not.

This is how the CreepJS works, and it is not a bug. The feedback is appreciated, but there is no issue with the code or the logic behind it. The issue is closed, but it can be re-opened, and code changes can be suggested if there is a better idea on how to handle rare fonts. Thank you for using CreepJS.

**Comment by igor-lemon** [comment]
It's a strange approach because Windows can have this font, albeit rarely. It's strange to consider it garbage and yet define the system as macOS. Especially when there are many other fonts that are unique to macOS. I would just replace this font with something that 100% doesn't exist on Windows.

**Comment by ttttmr** [comment]
A small suggestion, maybe changing to the font scoring method can improve this problem, for example, if there are more than 3 default fonts, it will be marked as the corresponding operating system

**Comment by abrahamjuliot** [comment]
The suggestions are good to consider. However, there is no font that is only available on Windows or macOS. The closest thing is the System UI CSS font, which can change depending on the operating system, but that is a different aspect of fingerprinting.

The current focus is on the data from CreepJS, which shows a wide range of font combinations between macOS and Windows users. In every case, these combinations are rare and affect less than 1% of users.

Changing fonts can have a significant impact on the fingerprinting training process. Therefore, it is important to evaluate the pros and cons of such changes and prioritize the most common scenarios over the edge cases.

**Comment by abrahamjuliot** [comment]
> ...define the system as macOS

At some point, we may change the label to `like macOS` or `like Windows` as discussed below. But it's not critical. 

- https://github.com/abrahamjuliot/creepjs/issues/178#issuecomment-1093604203

**Comment by Thorin-Oakenpants** [comment]
> However, there is no font that is only available on Windows or macOS

not really .... say `hello to my little friends` .... can I introduce you to `MS Shell Dlg`, `MS Shell Dlg 2` ... `-apple-system`. Now, it's feasible that an OS/browser can subtitute/alias those, but super highly unlikely

I have been looking into FontSubtitutes in windows. We also have the same thing in linux when fonts like `Courier`, `Arial`, `Times New Roman` are aliased, and mac does something similar which I am looking at next

detection of a change in measurements vs the control (base font) does not mean you have the font, it means the browser changed the font used (as per OS, browser settings) - and that size is in itself the entropy - e.g. a japanese windows install maps `MS Shell Dlg` differently to all other window installs. A Japanese system local adds unique aliases. An arabic system locale does the same.

**Comment by igor-lemon** [comment]
> At some point, we may change the label to `like macOS` or `like Windows` as discussed below. But it's not critical.

I don't know, but you say that my fonts are suspicious, but it's not true.
![image](https://github.com/abrahamjuliot/creepjs/assets/14764799/642823b1-a2f7-4211-8a46-327de5395ed9)

**Comment by igor-lemon** [comment]
> > ...define the system as macOS
> 
> At some point, we may change the label to `like macOS` or `like Windows` as discussed below. But it's not critical.
> 
> * [False positive when Linux has Windows fonts setup as UI fonts #178 (comment)](https://github.com/abrahamjuliot/creepjs/issues/178#issuecomment-1093604203)

I don't know, but you say that my fonts are suspicious, but it's not true.
<img width="687" alt="image" src="https://github.com/abrahamjuliot/creepjs/assets/14764799/f89ec044-25ff-455d-bcbc-128c21bffc53">

**Comment by abrahamjuliot** [comment]
> MS Shell Dlg, MS Shell Dlg 2

Nice. I need to take a closer look at this.

@igor-lemon I will reconsider this and keep you posted on changes.

**Comment by igor-lemon** [comment]
@abrahamjuliot If you need I can give you some macOS-only fonts since 10.14

**Comment by Thorin-Oakenpants** [comment]
> Nice. I need to take a closer look at this

Aww come on :) Don't you remember marveling at [my sheer genius](https://github.com/arkenfox/TZP/issues/34#issuecomment-1150887067) when I sped up font enumeration by doing a single pass on windows/mac (by comparing to to base font `MS Shell Dlg \\32` on windows and `-apple-system` on mac) instead of three passes (base fonts as monospace, sans-serif, serif) - and for three passes, I bailed if already found (most fonts if used will be detected against the first base font)

And this was further sped up by limiting the characters used in the font string - https://github.com/arkenfox/TZP/issues/216

**Comment by abrahamjuliot** [comment]
I'm way behind on trying that out. I might drop the use of Font Face API at some point. It's easily spoofed and unreliable.

**Comment by Thorin-Oakenpants** [comment]
I don't bother, since it seems to be blocked in TB and the results would be duplicitous IIUIC
