### ISSUE TITLE
Expand math fingerprinting

### ISSUE THREAD

**Issue by abrahamjuliot** [abrahamjuliot/creepjs#36]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math

- Include more static methods and properties
- Show unique results separate from Chrome V8

tests: https://es6console.com/kcvb8uvr/

Diff Tester:
https://jsfiddle.net/w3cqtsj1/ (consumes memory)

Polyfills:
https://jsfiddle.net/gz48qutr/14/

**Comment by abrahamjuliot** [comment]
`Math.sin()` in some cases returns different results in Tor Browser and Firefox.

```js
const bigN = 586084736227728400000000000000000000000
Math.sin(Math.PI)
// FF => 1.2246467991473532e-16
// TB => 1.2246063538223773e-16
Math.sin(bigN)
// FF => 0.994076732536068
// TB => -0.20876350121720488
```

**Comment by Thorin-Oakenpants** [comment]
I calculate **only 3 values in ECMA6** .. and I do all three differently to you: and mine can detect diffs between FF architecture, and certainly picks up on browser differences (safari !== chrome !== firefox !== edge (the non chrome one) !== internet explorer)

here is `exmpl(1)`
```js
		let n = 0.123
		let bigN = 5.860847362277284e+38
		let fns = [
			['acos', [n], 0],
			['acos', [Math.SQRT1_2], 1],
			['acosh', [1e308], 2],
			['acosh', [Math.PI], 3],
			['acosh', [Math.SQRT2], 4],
			['asin', [n], 5],
			['asinh', [1e300], 6],
			['asinh', [Math.PI], 7],
			['atan', [2], 8],
			['atan', [Math.PI], 9],
			['atanh', [0.5], 10],
			['atan2', [1e-310, 2], 11],
			['atan2', [Math.PI, 2], 12],
			['cbrt', [100], 13],
			['cbrt', [Math.PI], 14],
			['cos', [n], 15],
			['cos', [Math.PI], 16],
			['cos', [bigN],17], // unique in Tor
			['cosh', [1],18],
			['cosh', [Math.PI], 19],
			['expm1', [1],20], // <----------------------- this fucker
			['expm1', [Math.PI], 21],
			['exp', [n], 22],
			['exp', [Math.PI], 23],
			['hypot', [1, 2, 3, 4, 5, 6], 24],
			['hypot', [bigN, bigN], 25],
			['log', [n], 26],
			['log', [Math.PI], 27],
			['log1p', [n], 28],
			['log1p', [Math.PI], 29],
			['log10', [n], 30],
			['log10', [Math.PI], 31],
			['log10', [Math.E], 32],
			['log10', [Math.LN2], 33],
			['log10', [Math.LOG2E], 34],
			['log10', [Math.LOG10E], 35],
			['log10', [Math.SQRT1_2], 36],
			['log10', [Math.SQRT2], 37],
			['sin', [bigN], 38], // unique in Tor
			['sin', [Math.PI], 39], // unique in Tor
			['sin', [Math.E], 40],
			['sin', [Math.LN2], 41],
			['sin', [Math.LOG2E], 42],
			['sin', [Math.LOG10E], 43],
			['sin', [Math.SQRT1_2], 44],
			['sin', [Math.SQRT2], 45],
			['sinh', [1], 46],
			['sinh', [Math.PI], 47],
			['sinh', [Math.E], 48],
			['sinh', [Math.LN2], 49],
			['sinh', [Math.LOG2E], 50],
			['sinh', [Math.LOG10E], 51],
			['sinh', [Math.SQRT1_2], 52],
			['sinh', [Math.SQRT2], 53],
			['sqrt', [n], 54],
			['sqrt', [Math.PI], 55],
			['tan', [-1e308], 56],
			['tan', [Math.PI], 57],
			['tanh', [n], 58],
			['tanh', [Math.PI], 59],
			['pow', [n, -100], 60],
			['pow', [Math.PI, -100], 61],
			['pow', [Math.E, -100], 62],
			['pow', [Math.LN2, -100], 63],
			['pow', [Math.LN10, -100], 64],
			['pow', [Math.LOG2E, -100], 65],
			['pow', [Math.LOG10E, -100], 66],
			['pow', [Math.SQRT1_2, -100], 67],
			['pow', [Math.SQRT2, -100], 68]
		]
		let maths = []
		let test = Math.exp(1) - 1 // expm1(1)
		for(let i=0; i < fns.length; i++) {
			let fn = fns[i]
			let result = Math[fn[0]](...fn[1])
			maths.push(fn[2] + ": " + result)
			if (i==20) {
				maths.push("20.1:" + test)
			}
		}
```

But here's the diff when you calculate `exmpl(1)` my way (windows7)
```
		// FF60-67
		//- 20  : 1.718281828459045
		//- 20.1: 1.7182818284590455
		// FF68+
		//- 20  : 1.718281828459045
		//- 20.1: 1.718281828459045
```

See how `20.1` which is my method changes in 67- vs 68+.

here are some others I haven't tested against yours yet
```js
x = 0.5
return Math.log((1 + x) / (1 - x)) / 2 // atanh(0.5)  <--- this is your number 10

x= 1
let y = Math.exp(x)
return = (y - 1 / y) / 2 // sinh(1)  // this is your number 46
```

**Comment by abrahamjuliot** [comment]
I've thought about using polyfills, but it there are some cases where the engine/arch/os computation differs from the polyfill.

Example:
```js
// exmp1: false in Safari
(Math.exp(1) - 1) == Math.expm1(1)

// sinh: false in Safari
((Math.exp(Math.PI) - 1 / Math.exp(Math.PI)) / 2) == Math.sinh(Math.PI)

// atanh: false in Firefox, Chrome, Safari
n = 9e-8
(Math.log((1 + n) / (1 - n)) / 2) == Math.atanh(n)

// hypot from https://github.com/MaxArt2501/es6-math/blob/master/es6-math.js
// false in Chrome and Safari
function hypot(value1, value2) {
  let i, n = 0, args = arguments, len = args.length
  for (i = 0; i < len; i++) {
    n += args[i] * args[i]
  }
  return Math.sqrt(n)
}
let n = 5.860847362277284e+38
hypot(n, n) == Math.hypot(n, n)
```

**Comment by Thorin-Oakenpants** [comment]
> it appears there are some cases where the engine/arch/os computation differs from the polyfill

That's exactly what we want to be doing - it adds more entropy :)

**Comment by Thorin-Oakenpants** [comment]
so I tacked on the math test to the end of file:///D:/DLs/Torrents%20[In%20Progress]/TorZillaPrintBD/versions.html

Here is my modified ToDo entry in https://github.com/ghacksuserjs/TorZillaPrint/issues/66

> :small_blue_diamond: math
> * [ ] math: build a matrix (ECMAScript 1st vs 6th) of all results
>    - retest, create/test more Linux VM distros
>    - 99% sure this is all correct, but may find new hashes
> * [ ] math: research: see https://github.com/abrahamjuliot/creepjs/issues/36
>    - add more ECMA6 tests
>    - add polyfills: e.g. `((Math.exp(Math.PI) - 1 / Math.exp(Math.PI)) / 2) == Math.sinh(Math.PI)`
> * [ ] math: use a new math FP test for FF78+

So in a new test page, we could output the equation vs a polyfill (where applicable) like I did for those three: e.g. pad the number, pad the boolean and in fact I would color code the false red to stand out, and add a copy to clipboard button
```
00:  true, 1.4474840516030247, description
01: false: 0.7853981633974483, description
```

Then I can test it in FF78+, 32+64bit builds on OS-64bit, 32bit on OS-32bit. I have several VMs which I should expand. I have Windows7 32 + 64bit, Windows 10 (64bit), Mint 64, Mint 32, openSUSE, Ubuntu, Debian

I can already determine FF from other browsers (my ECMA1 cos tests do that): and I don;t think ECMA6 will provide any more entropy within FF. But I'm willing to do a heap on updating and setting up new VMs and testing and create a new FF78+ math test for it

We can create a list of the hashes as we find them and for each add the browser + version + build-bit + os-bit + OS-name and the results. When we have tested everything we can then compare each hash to see what is changing to get the items tested down to basic ... something like that

**Comment by abrahamjuliot** [comment]
>  ...output the equation vs a polyfill (where applicable)
> ...create a list of the hashes as we find them and for each add the browser + version + build-bit + os-bit + OS-name and the results. 

I like this idea.

**Comment by Thorin-Oakenpants** [comment]
> ```js
> // atanh: false in Firefox, Chrome, Safari
> n = 9e-8
> (Math.log((1 + n) / (1 - n)) / 2) == Math.atanh(n)
> ```

not much use if all three engines do the same (FF + chrome are same values, no idea about safari)

```
8.999999990174443e-8 <-- polyfill
9.000000000000024e-8 <-- function
```

When n = `0.5` they matched (which is test 10) - 10 shows up in 32bit TB60 (and 32bit FF67 and lower etc). I suspect a lot of these in FF are no longer applicable since FF68 (when they did something to the libm: compression) - I'm adding polyfills and am yet to find something that differs (in FF)

**Comment by Thorin-Oakenpants** [comment]
based on some old data (FP Central used polyfills [1]), only these three **had** (in older firefoxes - my notes only go to FF66)
- atanh, expm1, sinh

I used the above to decide what to limit my ECMA 6th edition tests to, and since 68 they no longer differ from chrome etc (AFAIK)

![image](https://user-images.githubusercontent.com/16656956/91660471-a40d1880-eac5-11ea-81f1-8f9b847a353a.png)

[1] https://fpcentral.tbb.torproject.org/fp/tor/mathRoutine.js

**Comment by abrahamjuliot** [comment]
Some interesting finds through attempts to mimic pow

```js
expected = 2.5600000000000008e-62

// custom 1
x = 2e-8;[...Array(3)].forEach((val, i) => x*=x)
x == expected // true in FF and Chrome

// native Math.pow(2e-8,8)
Math.pow(2e-8, 8) == expected// false in Chrome (yields 2.5600000000000003e-62)

// native exponentiation operator 2e-8**8 -- equivalent to Math.pow(2e-8,8) and implementation-dependent
2e-8**8 == expected // false in Chrome (yields 2.5600000000000003e-62)

// custom 2
2e-8*2e-8*2e-8*2e-8*2e-8*2e-8*2e-8*2e-8 == expected // false in FF and Chrome (yields 2.5600000000000003e-62)

// custom 3: altering the operation order changes the result
2e-8*2e-8*2e-8*2e-8*(2e-8*2e-8*2e-8*2e-8) // true in FF and Chrome
```

**Comment by abrahamjuliot** [comment]
> ...all three engines

`((Math.exp(Math.PI) - 1 / Math.exp(Math.PI)) / 2)` is the same in FF, Chrome, Safari, but Math.sinh(Math.PI) is different in Safari.

> polyfills 

From what I gather, the entropy obtained through a polyfill (if any) can be reduced to testing the implementation-dependent methods: `log`, `pow`, `exp`, `sqrt` etc. A polyfill free from native methods should yeild the same result across systems. Entropy is introduced when the calculation uses an implementation-dependent method (or operator in the case of **). This is just my limited observation, however.

**Comment by Thorin-Oakenpants** [comment]
> the implementation-dependent methods: `log`, `pow`, `exp`, `sqrt` etc

- All I know is it the older ones (if that's the right word) that gives me the entropy within FF (I only needed to use 8 `cos` tests). 
- ^^ So if something based on `cos` that has entropy, is then used in a polyfill, then that polyfill also gets entropy
- FF68+ seems to now be consistent in the newer ones (ECMA6?), but we can test more
- The newer ones seems to give entropy between engines (which to me is less important)
- [I'm lost](https://en.wikipedia.org/wiki/ECMAScript#Versions) - is there a list somewhere of what math functions belong to what ECMA version?
- I don't know how browsers choose or use or bundle math or libm's, or if the OS is used for some math functions
- I don't really know what I'm talking about 😀 , but I do try :) 

---

There's two things going on here
- **A**: I can already detect FF, so the entropy (for me) within FF is the most important thing, and so far I see none of that with ECMA 6th edition (not since FF68), but tests will be a better indicator
- **B**: entropy between engines (see pic of Opera): running my test in chromium for example, shows a lot of diffs between chromium and FF (FF is the control), so expanding the ECMA tests in TZP to include some of these (I'll use the old math function in 67- and a new one in 78+) is OK, not essential for me (see previous point)
- we need to finish the list of math tests and then do some actual tests on browsers. I see you added a shitload more tests. See my issue [here](https://github.com/ghacksuserjs/TorZillaPrint/issues/78) - I've now set up the framework
   - I'm using user-specified numbers so we can easily refer to them
   - after testing every browser in all configs (bit build, os, os build, version), all the "numbers in play" will give us a list of meaningful math tests for max entropy: some may still be redunant, but at least we can weed out the ones that do not make a difference
   - I need a better way to auto-generate the polyfills since each `type` uses the same method. At the moment I've manually added them

**feel free** to chime in on the other issue at TZP

Opera: note: I only have 6 polyfills set up
![image](https://user-images.githubusercontent.com/16656956/91671909-1f98b500-eb1a-11ea-937d-8bd98539c1ac.png)

**Comment by abrahamjuliot** [comment]
There's nice short list of es6 functions at https://github.com/MaxArt2501/es6-math/blob/master/README.md#usage
