### ISSUE TITLE
screen vs iframe

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [abrahamjuliot/creepjs#91]
So on android I get trashed (with or without RFP)

```
1. screen: 414, 761, 414, 764, 414, 24, 24] does not match iframe
```

screen itself is reported as
```
device: unknown
width: 300
outerWidth: 300
availWidth: 300
height: blocked
outerHeight: blocked
availHeight: blocked
colorDepth: 24
pixelDepth: 24
```

So two questions
- how are you getting metrics from an iframe? is this just screen, window properties? if window isn't that referring to the iframe metrics?
- why is height blocked - I don't get height blocked in TZP .. what are you doing differently?

TIA

**Comment by abrahamjuliot** [comment]
Yes, the iframe metric is computed here.
https://github.com/abrahamjuliot/creepjs/blob/762ebbe78241a4981e1f5d9f87add5ecc9c51657/modules/lies.js#L21

The `contentWindow` variable name is misleading -- it's just an iframe window. I think this issue is only in iframe windows and not in `iframe.contentWindow`.

`300x0` [0 for blocked] is due to me styling `height: 0` to fake display none behavior along with `visibility:hidden` (`display:none` doesn't reveal screen in FF). This style works on desktop with no RFP, but I'm not sure why Android (and RFP in general) defaults to `300x150` in frame windows. If I set `width: 100%` I can get the actual width, but max height is 150. 

For now, I think this can be clear this by discarding the iframe screen test or testing screen in iframe.contentWindow instead of iframe window.

**Comment by Thorin-Oakenpants** [comment]
Let me know if there is anything to add to TZP
- for example I am looking at vh units and this iframe thing also interests me
- note I can display the information based on my own isAndroid boolean (the value is unknown until later in the script, but I grab values as soon as possible - as the native resolution is not the same as the TZP page which dictates a set width, for a reason) - I don't expect an iframe to get anything in time - so maybe not relevant for TZP? IDK

**Comment by abrahamjuliot** [comment]
I think it's fixed now. Based on your input, I added:
- `100vh` and `100vw` to get the viewport
- `position: absolute; left: -10000px;` to remove scroll wobbling. Absolute position also keeps the viewport stable against resize noise (when not RFP).

> Metrics

On desktop only, the former test works on desktop without RFP (tested on Win10 FF 82-83 and Nightly). I get an accurate result `1280x800`. It appears to work on Android FF 83 too, but I'm using Chromebook tablet (also `1280x800`).

![image](https://user-images.githubusercontent.com/6946045/100051045-b39fb300-2dcf-11eb-8a27-2286f996b01b.png)


> TZP

Here's a simplified gist of the function. Since the iframe is without a src, results should be fast. I use this mostly to obtain a clean context (if available) and make comparison tests, but I don't think this screen comparison test has great value. It depends on the tampering, but results can be inconsistent. If popular screen dimensions are spoofed, the comparison can match the actual screen at random.

```js
const getNestediFrameWindow = () => {
    const numberOfIframes = window.length
    const div = document.createElement('div')
    div.setAttribute('style', 'display:none')
    document.body.appendChild(div)
    const id = 'parent-nest'
    const ghost = `
	style="
		height: 100vh;
		width: 100vw;
		position: absolute;
		left: -10000px;
		visibility: hidden;
	"
	`
    div.innerHTML = `
	<div ${ghost} id="${id}">
		<iframe ${ghost}></iframe>
	</div>
	`
    const el = document.getElementById(id)
    return {
        parent: !!el,
        iframeWindow: window[numberOfIframes],
        remove: () => el.parentNode.removeChild(el)
    }
}

const nest = getNestediFrameWindow()

console.log('matching: ', nest.iframeWindow.screen.width == screen.width)

if (nest.parent) {
    nest.remove()
}
```

**Comment by Thorin-Oakenpants** [comment]
RFP returns all zeros (desktop)

```js
	let w1 = nest.iframeWindow.screen.width, h1 = nest.iframeWindow.screen.height,
		w2 = nest.iframeWindow.screen.availWidth, h2 = nest.iframeWindow.screen.availHeight,
		w3 = nest.iframeWindow.window.outerWidth, h3 = nest.iframeWindow.window.outerHeight,
		w = nest.iframeWindow.window.innerWidth, h = nest.iframeWindow.window.innerHeight
```

no RFP
```
0 | 2560 | 1440
1 | 2560 | 1378
2 | 1014 | 1114
3 | 0 | 0
```

RFP
```
0 | 0 | 0
1 | 0 | 0
2 | 0 | 0
3 | 0 | 0
```

I'm a little confused, but that's OK. I wanted to test vh units differently - so forget that for now. But this was already on my radar - everything that can be checked via iframes or workers (all methods) needs to be added to each of the TZP sections (and thus lies exposed), and AFAICT this is just an iframe returning screen and window properties? right? (forget all the different iframe methods for now)

**Comment by abrahamjuliot** [comment]
Yes, it's just an iframe returning window properties along with screen. Since injection and styling causes a dom [reflow + repaint](https://developers.google.com/speed/docs/insights/browser-reflow), opting out can improve overall performance. Pages with complex and deep dom trees will benefit the most.

> RFP returns all zeros (desktop)

I'm not sure why, but on certain pages including TZP, removing the line `div.setAttribute('style', 'display:none')` fixes this issue. I'm guessing the body and child inherited css positioning affects the iframe position.

**Comment by Thorin-Oakenpants** [comment]
Thanks. I took a bit of a break for a week, but am mostly back into it now. So many things to do in TZP, I'm not sure where to carry on from. I guess just tackling each section: promisifying, adding in iframe/worker tests, detecting lies, and outputting section hashes (as opposed to adding anything new right now). This test for iframe will happen naturally as I get around to the screen section
