### ISSUE TITLE
Android emulator detection BlueStacks and Genymotion

### ISSUE THREAD

**Issue by MikhailCarpov** [abrahamjuliot/creepjs#94]
I have tested android emulators for windows.
 1) Emulators have the "platform: linux i686" parameter. Test phones must have a platform arm. Is this an argument for spoofing detection? 
2) BlueStacks emulator doesn't have a working api speech for the latest chrome. Is this an argument for spoofing detection? 
3) Genymotion has a mention of emulation. See the webgl on the screen.
4) To improve the quality of phone spoofing detection, you can use the Gyroscope api.

![Genymotion 2020-12-01 07 17 06](https://user-images.githubusercontent.com/66925827/100697831-1680e380-33a8-11eb-9957-bf86e5d64315.png)
![Genymotion 2020-12-01 07 17 23](https://user-images.githubusercontent.com/66925827/100697835-17197a00-33a8-11eb-8533-67344df29ec1.png)
![Genymotion 2020-12-01 07 17 32](https://user-images.githubusercontent.com/66925827/100697836-17b21080-33a8-11eb-9776-bd877b38aae8.png)
![BlueStacks  2020-12-01 07 18 36](https://user-images.githubusercontent.com/66925827/100697837-184aa700-33a8-11eb-88f8-7386235f52aa.png)
![BlueStacks  2020-12-01 07 18 52](https://user-images.githubusercontent.com/66925827/100697839-184aa700-33a8-11eb-8c86-6953a64b4801.png)
![BlueStacks 2020-12-01 07 18 42](https://user-images.githubusercontent.com/66925827/100697840-18e33d80-33a8-11eb-92a6-eb51ac2c6707.png)

**Comment by abrahamjuliot** [comment]
Nice catch. This will now render in the template as "Android [emulator]". I tested this in BlueStacks and Android VirtualBox. 

I see these static irregularities in emulators as noteworthy, but not on the same level as spoofing (API tampering or random noise). Since emulators, as far as I know, are not hostile to fingerprinting, and the browsers running on them can be trusted in many contexts (with or without the Speech API), these can be welcomed as unique and fair. Webgl, platform/userAgent, and the unsupported Speech API ultimately give the device and browser a unique fingerprint.

However, in #95, I can expand on a platform/userAgent test to detect mismatches (including android without arm). The detected mismatch would be collected in the loose fingerprint trash bin since machine spoofing can mismatch and appear genuine at random (causing instability). As the loose fingerprint count increases, the browser will lose score points. Some user agent switchers don't match the user agent and platform, so every time a mismatch is triggered, points will be taken.

> Gyroscope API

Interesting. I will give this more research. It requires permission that may not carry across sessions. But, I wonder if there is a leak in the Sensor API. I'm adding this to #48.

**Comment by abrahamjuliot** [comment]
Closing for now. I observed some false positives in emulator detection. There are many types that are not very straightforward to detect.
